'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PortalNoticiasBDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PortalNoticiasBDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categoria() As DbSet(Of Categoria)
    Public Overridable Property Comentario() As DbSet(Of Comentario)
    Public Overridable Property Debate() As DbSet(Of Debate)
    Public Overridable Property Noticia() As DbSet(Of Noticia)
    Public Overridable Property Preferencia() As DbSet(Of Preferencia)
    Public Overridable Property Puntuacion() As DbSet(Of Puntuacion)
    Public Overridable Property Sugerencia() As DbSet(Of Sugerencia)
    Public Overridable Property Usuario() As DbSet(Of Usuario)

End Class
